# Generated by Django 5.1.4 on 2025-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_staff_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='qualification',
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.ManyToManyField(to='clinic.qualification'),
        ),
    ]
