# Generated by Django 5.1.4 on 2025-01-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_staff_qualification_staff_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='clinic.specialization'),
        ),
    ]
