# Generated by Django 5.1.4 on 2025-01-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='qualification',
        ),
    ]
