# Generated by Django 5.1.4 on 2025-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_specialization_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.ManyToManyField(to='clinic.qualification'),
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='education_qualification',
        ),
        migrations.AddField(
            model_name='receptionist',
            name='education_qualification',
            field=models.ManyToManyField(to='clinic.qualification'),
        ),
    ]
