# Generated by Django 5.1.4 on 2025-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
